### ISSUE TITLE
YAML is not nested

### ISSUE THREAD

**Issue by floydback** [simplelocalize/simplelocalize-cli#54]
```
simplelocalize download \
        --apiKey MY_API_KEY \
        --downloadFormat yaml \
        --downloadPath ./src/locales/{lang}.yaml \
        --downloadOptions WRITE_NESTED \
```
This gives me non nested yaml:

```
---
# Generated by simplelocalize.io
btn.browse.another: '他のファイルを選択する'
btn.browse.reading: '読むこと ...'
```

What I've expected
```
---
# Generated by simplelocalize.io
btn:
  browse:
    another: '他のファイルを選択する'
btn:
  browse:
    reading: '読むこと ...'
```

**Comment by floydback** [comment]
Seems quotes are not escaped
`btn.howit.title: 'How it's work'`

**Comment by jpomykala** [comment]
Hey @floydback 

WRITE_NESTED was not supported in the YAML format, but I implemented it now. I removed single quotes from translations because they were unnecessary in this case. 

Using a YAML format with `WRITE_NESTED` option will output a file like this:

```
---
# Generated by simplelocalize.io
btn:
  browse:
    another: 他のファイルを選択する
    reading: 読むこと ...
```
